### PR TITLE
add package.json

### PR DESCRIPTION
**Pull request by juliangruber**
using browserify's `browser` field you can make it work without modifying code.

### CODE REVIEW

**Comment by juliangruber** [comment]
oh and you'd have to pick another name or point people to github style dependencies in npm

**Comment by adamsanderson** [comment]
@juliangruber, so what do folks normally do? Something like `caret-component`, `adamsanderson/caret`, or what?

**Comment by juliangruber** [comment]
I prefer installing from npm as github is down more often

**Comment by adamsanderson** [comment]
@juliangruber, I'll totally add the package.json, I'm just curious about naming conventions.

**Comment by juliangruber** [comment]
Components that are on npm are usually named like:
- `<repo>` (if available)
- `<repo>`-component
- component-`<repo>`

**Comment by adamsanderson** [comment]
Pulled in another package.json.  A mere two and a half years later.

Well, better this decade than never.

**Comment by juliangruber** [comment]
what a badass way to end a pull request!

**Pull request closed without merging**
